### ISSUE TITLE
Header row with additional characters when using python27

### ISSUE THREAD

**Issue by gurisko** [firecat53/tabview#86] opened 2015-01-31 01:19 UTC
I updated code after a longer period and I found out that encoding no longer properly works for python 2.7.6 but it works as expected for python 3.4.1.
I am using this CSV file for testing: http://www.andrewpatton.com/countrylist.html

**Comment by firecat53** [comment] 2015-01-31 06:23
Are you using the current master branch, or the last Pypi release? That CSV file works fine here with both python 2.7 and 3.4. Can you provide a traceback of the error?

Thanks!

**Comment by gurisko** [comment] 2015-01-31 12:31
Sorry my fault - the problem seems to be just in the header row when there are some additional characters. So it is not a wrong encoding problem. I am using the current master branch and there is no traceback.
![image](https://cloud.githubusercontent.com/assets/495549/5988014/e509c66e-a94c-11e4-816f-6acad3d577c6.png)
Environment: OSX 10.10.1, python 2.7.6

**Comment by wavexx** [comment] 2015-01-31 13:19
I also cannot reproduce the issue.
Could you try to specify manually the encoding parameter?

**Comment by firecat53** [comment] 2015-01-31 16:33
Zip up the file exactly as you have it and either email it or post it someplace I can download. Maybe it has to do with the encoding that it acquired when you downloaded it.

Thanks!

**Comment by firecat53** [comment] 2015-01-31 23:14
Maybe you got a corrupted download...the file you sent me was exactly equal to the file I downloaded from that site and it worked fine in both 2.7 and 3.4. There aren't even any 'special' characters in the header row...it all looks to be straight ASCII letters/numbers.

**Comment by firecat53** [comment] 2015-02-02 19:17
If you can find a consistent way to reproduce this error (on more than 1 machine), please post it. Otherwise I'll go ahead close this pending more information.

**Comment by gurisko** [comment] 2015-02-02 19:28
@firecat53 I will try to reproduce this again. I will inform you soon. Thanks!

**Comment by gurisko** [comment] 2015-02-03 12:35
So far I can say that this happens because of the default `trunc_char`. If I replace it with something like `>` it works as expected. So from my point of view there is a minor bug somewhere in encoding and it occurs due to my environment settings.

**Comment by wavexx** [comment] 2015-02-03 13:01
On 02/03/2015 01:35 PM, Matus Gura wrote:
> So far I can say that this happens because of the default
> `trunc_char`. If I replace it with something like `>` it works as
> expected. So from my point of view there is a minor bug somewhere in
> encoding and it occurs due to my environment settings.

What's your terminal encoding then? (it's usually determined by the
LC_CTYPE/LC_ALL/LANG environment variables.

Can you render other utf-8 text? (see the sample files)

**Comment by gurisko** [comment] 2015-02-03 13:07
My terminal: `$LANG = en_US.UTF-8`. No, I can't render correctly `sample/unicode-example-utf8.txt` (with python27)

**Comment by wavexx** [comment] 2015-02-03 13:08
On 02/03/2015 02:07 PM, Matus Gura wrote:
> My terminal: `$LANG = en_US.UTF-8`. No, I can't render correctly `sample/unicode-example-utf8.txt` (with python27)

Which terminal is this?

**Comment by gurisko** [comment] 2015-02-03 13:16
>Which terminal is this?

`xterm-256color`

**Comment by firecat53** [comment] 2015-02-03 14:59
Try this little patch and see if it changes anything. This is really hard to debug without being able to reproduce! I tried xterm and had no issues.

    @@ -92,7 +92,7 @@ class Viewer:
         self._get_column_widths(column_width)
 
         try:
-            trunc_char.encode(sys.stdout.encoding or 'utf-8')
+            trunc_char.encode(detect_encoding() or 'utf-8')
             self.trunc_char = trunc_char
         except (UnicodeDecodeError, UnicodeError):
             self.trunc_char = '>'

**Comment by gurisko** [comment] 2015-02-04 13:34
Both `sys.stdout.encoding` and `detect_encoding()` returns the same value `UTF-8`. In a basic script this throws exception but not in tabview.

**Comment by firecat53** [comment] 2015-02-04 14:37
Does the viewer cause heading issues for _any_ file using python 2.7, or just that one file? I still can't reproduce this :frowning:

**Comment by gurisko** [comment] 2015-02-05 11:30
It occurs also for all files except `multiindex.csv` from sample dir

**Comment by firecat53** [comment] 2015-02-05 14:28
Hrm, well, lets start from scratch:

1. What distro/platform? Which terminal? Does it happen on all terminals or just xterm? Can you reproduce it on another machine/VM with the same terminal/encoding?
2. Uninstall tabview. Check for stale versions in /usr/lib/python2.7/site-packages/ and .local/lib/site-packages/ (This burned me once)
3. Create a python 2 virtualenv and activate
4. Clone the git repo
5. python setup.py install OR pip install -e .

**Comment by firecat53** [comment] 2015-06-28 02:18
Closing. If you have more info for me, feel free to re-open!

**Closed by firecat53** 2015-06-28 02:18 UTC
